<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            padding: 20px 0;
            border-bottom: 3px solid #667eea;
            margin-bottom: 30px;
        }
        
        .header h1 {
            color: #667eea;
            font-size: 28px;
            margin-bottom: 10px;
        }
        
        .header p {
            color: #666;
            font-size: 14px;
        }
        
        .info-section {
            background: #f9fafb;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        
        .info-row {
            display: flex;
            padding: 8px 0;
            border-bottom: 1px solid #e5e7eb;
        }
        
        .info-row:last-child {
            border-bottom: none;
        }
        
        .info-label {
            font-weight: 600;
            width: 150px;
            color: #374151;
        }
        
        .info-value {
            color: #6b7280;
        }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin-bottom: 30px;
        }
        
        .stat-box {
            background: #f3f4f6;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }
        
        .stat-value {
            font-size: 24px;
            font-weight: 700;
            color: #667eea;
            margin-bottom: 5px;
        }
        
        .stat-label {
            font-size: 12px;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .section-title {
            font-size: 20px;
            font-weight: 700;
            color: #1f2937;
            margin: 30px 0 15px 0;
            padding-bottom: 10px;
            border-bottom: 2px solid #e5e7eb;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        thead {
            background: #667eea;
            color: white;
        }
        
        th {
            padding: 12px;
            text-align: left;
            font-weight: 600;
            font-size: 14px;
        }
        
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 13px;
        }
        
        tbody tr:hover {
            background: #f9fafb;
        }
        
        .status-badge {
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
            display: inline-block;
        }
        
        .status-present {
            background: #d1fae5;
            color: #065f46;
        }
        
        .status-absent {
            background: #fee2e2;
            color: #991b1b;
        }
        
        .status-late {
            background: #fef3c7;
            color: #92400e;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
        }
        
        @media print {
            body {
                padding: 0;
            }
            
            .header {
                page-break-after: avoid;
            }
            
            table {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>{{ $data['report_title'] }}</h1>
        <p>Generated: {{ $data['generated_at']->format('F d, Y h:i A') }}</p>
        <p>Generated by: {{ $data['generated_by'] }}</p>
    </div>

    @if($reportType === 'event')
        <!-- Event Information -->
        <div class="info-section">
            <div class="info-row">
                <div class="info-label">Event Name:</div>
                <div class="info-value">{{ $data['event']->title }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Event Date:</div>
                <div class="info-value">{{ \Carbon\Carbon::parse($data['event']->start_time)->format('F d, Y') }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Event Time:</div>
                <div class="info-value">
                    {{ \Carbon\Carbon::parse($data['event']->start_time)->format('g:i A') }} - 
                    {{ \Carbon\Carbon::parse($data['event']->end_time)->format('g:i A') }}
                </div>
            </div>
        </div>

        <!-- Statistics -->
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['registered'] }}</div>
                <div class="stat-label">Registered</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['present'] }}</div>
                <div class="stat-label">Present</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['absent'] }}</div>
                <div class="stat-label">Absent</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['attendance_rate'] }}%</div>
                <div class="stat-label">Attendance Rate</div>
            </div>
        </div>

        <!-- Attendance Records -->
        <h2 class="section-title">Attendance Records</h2>
        <table>
            <thead>
                <tr>
                    <th>Member Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['attendances'] as $attendance)
                <tr>
                    <td>{{ $attendance->member->name }}</td>
                    <td>{{ $attendance->member->email ?? 'N/A' }}</td>
                    <td>{{ $attendance->member->phone ?? 'N/A' }}</td>
                    <td>
                        <span class="status-badge status-{{ $attendance->status }}">
                            {{ ucfirst($attendance->status) }}
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

    @elseif($reportType === 'member')
        <!-- Member Information -->
        <div class="info-section">
            <div class="info-row">
                <div class="info-label">Member Name:</div>
                <div class="info-value">{{ $data['member']->name }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Email:</div>
                <div class="info-value">{{ $data['member']->email ?? 'N/A' }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Phone:</div>
                <div class="info-value">{{ $data['member']->phone ?? 'N/A' }}</div>
            </div>
        </div>

        <!-- Statistics -->
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['total_events'] }}</div>
                <div class="stat-label">Total Events</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['present'] }}</div>
                <div class="stat-label">Present</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['absent'] }}</div>
                <div class="stat-label">Absent</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['attendance_rate'] }}%</div>
                <div class="stat-label">Attendance Rate</div>
            </div>
        </div>

        <!-- Attendance Records -->
        <h2 class="section-title">Event Attendance History</h2>
        <table>
            <thead>
                <tr>
                    <th>Event Name</th>
                    <th>Event Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['attendances'] as $attendance)
                <tr>
                    <td>{{ $attendance->event->title }}</td>
                    <td>{{ \Carbon\Carbon::parse($attendance->event->start_time)->format('M d, Y') }}</td>
                    <td>
                        <span class="status-badge status-{{ $attendance->status }}">
                            {{ ucfirst($attendance->status) }}
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

    @elseif($reportType === 'summary')
        <!-- Overall Statistics -->
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['total_events'] }}</div>
                <div class="stat-label">Total Events</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['total_members'] }}</div>
                <div class="stat-label">Total Members</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['present'] }}</div>
                <div class="stat-label">Total Present</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['overall_rate'] }}%</div>
                <div class="stat-label">Overall Rate</div>
            </div>
        </div>

        <!-- Top Events -->
        <h2 class="section-title">Top 5 Events by Attendance</h2>
        <table>
            <thead>
                <tr>
                    <th>Event Name</th>
                    <th>Date</th>
                    <th>Present Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['top_events'] as $event)
                <tr>
                    <td>{{ $event->title }}</td>
                    <td>{{ \Carbon\Carbon::parse($event->start_time)->format('M d, Y') }}</td>
                    <td>{{ $event->attendances->where('status', 'present')->count() }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

    @elseif($reportType === 'date_range')
        <!-- Date Range Info -->
        <div class="info-section">
            <div class="info-row">
                <div class="info-label">Date Range:</div>
                <div class="info-value">{{ $data['date_range']['start'] }} to {{ $data['date_range']['end'] }}</div>
            </div>
        </div>

        <!-- Statistics -->
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['total_events'] }}</div>
                <div class="stat-label">Total Events</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['present'] }}</div>
                <div class="stat-label">Present</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['absent'] }}</div>
                <div class="stat-label">Absent</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $data['stats']['attendance_rate'] }}%</div>
                <div class="stat-label">Attendance Rate</div>
            </div>
        </div>

        <!-- Attendance Records -->
        <h2 class="section-title">Attendance Records</h2>
        <table>
            <thead>
                <tr>
                    <th>Event</th>
                    <th>Date</th>
                    <th>Member</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['attendances'] as $attendance)
                <tr>
                    <td>{{ $attendance->event->title }}</td>
                    <td>{{ \Carbon\Carbon::parse($attendance->attendance_date)->format('M d, Y') }}</td>
                    <td>{{ $attendance->member->name }}</td>
                    <td>
                        <span class="status-badge status-{{ $attendance->status }}">
                            {{ ucfirst($attendance->status) }}
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <!-- Footer -->
    <div class="footer">
        <p>This report was automatically generated by the Attendance Management System</p>
        <p>© {{ date('Y') }} All rights reserved</p>
    </div>

    <script>
        // Auto-print on load
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>